### ISSUE TITLE
Failed Setup, will retry: none

### ISSUE THREAD

**Issue by rbhun** [andrewleech/uhoo-homeassistant#4]
-New HA green hardware, plus a Z-wave stick
-core: 2024.7.4, OS 12.4
-uhoo from HACS, version is stated as 0.0.4 from @andrewleech  in the HACS page, 0.0.5 in the Integration page 

Uhoo is installed and then configured, accepts user and password. Then says: Failed Setup, will retry:none

I have these in the log:
Error: an exception occurred while attempting to get latest data: Error requesting data from https://api.uhooinc.com/v1/getalllatestdata: 400, message='Bad Request', url=URL('https://api.uhooinc.com/v1/getalllatestdata')

also have this:
This error originated from a custom integration.

Logger: custom_components.uhoo
Source: helpers/update_coordinator.py:344
integration: uHoo (documentation, issues)
First occurred: 03:25:18 (12 occurrences)
Last logged: 03:32:55

Error fetching uhoo data:

just for fun I tried the webpage linked and it indeed says invalid.

**Comment by andrewleech** [comment]
Hmm, my install seems to be working. The version numbers reported are confusing, which made me realise I never tagged my "current" version as a release. 

I've just done so, as v0.0.5 

Maybe check if hacs offers this as an update now?

**Comment by rbhun** [comment]
Hi
I am fairly new to HACS, so I am not sure where, but I do not see such an option. 

If I go to HACS - integration - uhoo I get this, still saying 0.0.4 ( I hope pics go thru from email)
￼

in fact, if I click on 'release 0.0.4'  it it opens the github page and thats still 0.0.4 too.
UPDATE: it opens the @csacca github. Is that okay? this came from your page..

the integration still looks like this:

￼

**Comment by andrewleech** [comment]
I'm not getting the pictures sorry, but yeah 0.0.4 is a release from the original csacca repo, not mine, so it looks like maybe that's what's installed instead?

**Comment by andrewleech** [comment]
Oh...
I originally made my changes here as a pull request into csacca repo, not expecting people to ever need to install directly from here. 
However csacca repo hasn't been updated since / my changes never got merged.

I never updated the instructions in the readme on this fork to show how to install directly from this repo, so the instructions still give the url for the original csacca one.

**Comment by andrewleech** [comment]
Ok, I've just updated the readme to hopefully make this easier! 
You're probably best to remove your current copy from hacs and try again from the updated instructions on the front page of this repo.

**Comment by rbhun** [comment]
I just deleted the current uhoo setup
I added a custom repo of: https://github.com/andrewleech/uhoo-homeassistant/archive/refs/tags/v0.0.5.tar.gz and installed it.
the top of the hacs page says 0.0.5, @andrewleech, @csacca.  at Release, it says 0.0.4. 
clicking on it, the github page still says 0.0.4 and I have the same error.

**Comment by rbhun** [comment]
![image](https://github.com/user-attachments/assets/deffaa30-9e0e-4dd0-b06e-7a657b3e35ee)

**Comment by rbhun** [comment]
![image](https://github.com/user-attachments/assets/d696d06f-3186-4b59-a8b5-61f492b6cfd9)

**Comment by rbhun** [comment]
here you can see me using your new readme, selecting 0.0.5. On the top left, you can still see the tag 0.0.4


Unfortunately, I get the same error.

**Comment by andrewleech** [comment]
Did you restart home assistant in between? It does look like it's still using the old one.

**Comment by rbhun** [comment]
yes I did a full restart. I tried it before and after I logged in with the uhoo creditentials.

**Comment by andrewleech** [comment]
On the hacs page, bring up custom repositories again and just double check the url for the repo, eg.


![Screenshot_20240805-210841.png](https://github.com/user-attachments/assets/bf75dfef-af7b-47c3-8e1d-555af090afc4)

---

![Screenshot_20240805-210854.png](https://github.com/user-attachments/assets/68dd30e3-12a9-4573-a688-5e4fc2c3313f)


and then back on the hacs main page see if it's listed as "pending update" like mine, if so hit the update button. 


![Screenshot_20240805-211119.png](https://github.com/user-attachments/assets/993a2c42-6868-4362-a83d-579749c49054)

**Comment by rbhun** [comment]
yes, it looks like this:
![image](https://github.com/user-attachments/assets/e1f4bacd-148e-422e-9114-801d2a51350d)
and if I open it from the list, and click on the repository under the 3 dots here, it takes me to you github.
![image](https://github.com/user-attachments/assets/f8fd330a-a533-426b-9549-64be3bf191a6)

after I download it, I get a Pending Restart:
![image](https://github.com/user-attachments/assets/ae53adc7-0fa3-4516-ae4a-a48e56280b12)

**Comment by andrewleech** [comment]
I've made another new release tag v0.0.6 just to include the readme changes.
If you update to that then the rest of the display for uhoo integration should show the correct version too.

Hopefully after that and the home assistant restart it works for you. 

I haven't tested logging in from scratch with a new install for a while so there's still a chance something has gone wrong there, but hopefully not!

**Comment by rbhun** [comment]
I deleted all traces (hopefully), even the custom repo from the HACS window. I have rebooted (not just restarted after delete.
I have then installed the new repo, using the link from the new readme. It does show 0.0.6, along with 0.0.5. However, in the corner, it still says 0.0.04, and that tag links to the old github page.
![image](https://github.com/user-attachments/assets/1fac0e40-758c-4757-99d0-01b1ad3376ab)
After I downloaded this, I got a prompt to restart. I rebooted again, and installed the integration. 
Unfortunately, it is still the same result. I dont get it..

PS: I am not sure it matters, but the Configure window looks like this:
![image](https://github.com/user-attachments/assets/f3bc7d23-c5ab-415f-82ad-a1f8704d7ed2)

**Comment by rbhun** [comment]
Sorry I still cannot get this working. 
-do I need an uHoo premium subscription?
-what is the correct URL? I assume https://api.uhooinc.com/v1/getalllatestdata is not it.

**Comment by andrewleech** [comment]
I haven't paid for premium, I don't think it's that.

Oh, I see now in your previous pictures about the versions, I think mine does show all the same as you now. That 0.0.4 is the GitHub badge picture, that link in the readme must still be wrong sorry. 

Perhaps yours is correctly installed now, which doesn't explain why the setup fails. 

There's a chance the setup process in the integration is actually broken, maybe it's been broken by a recent home assistant update or something. My copy has been installed and untouched for a long time now. 

I'll have to try resetting my installation and go through the setup process myself to see what's going on, which will have to wait until I'll have a little bit of time free to fix anything needed when I do so to keep my uhoo working.

**Comment by rjkrom** [comment]
Is there any news on this repo? I have the same issue as  rbhun. Are we one of the few experiencing this issue? Curious if @andrewleech did have the time to look into the issue?

**Comment by andrewleech** [comment]
No I haven't had time to look closer, though considering there's a few reports now it certainly sounds like there's a common issue with initial log in. 

My existing installation is still working correctly so most of the server configuration is presumably still correct and valid, just something has changed with the login. 

Between having a very young family and busy work I don't have much time for personal projects like this lately, but this issue is on my list to look at eventually - just really can't give much indication when that might be sorry.

**Comment by rjkrom** [comment]
I can fully understand that this is not your first priority in your situation. Of course I hope you will find some time for this issue. Thank you and cheers!

**Comment by frankvandenhurk** [comment]
same problem here, please let me know if I can help (e.g. testing)

**Comment by srescio** [comment]
hi folks

TL;DR

1. open you uHoo mobile app
2. tap hamburgher menu
3. Appearance
4. Temperature
5. Change it to whatever else you currently have and save
6. Change it back to you previous setting

Issue is in the pyuhoo library trying to access the temperature unit selection from somewhere that is not anymore guaranteed to be present, reselecting the unit makes the API return again said field, without which the unhandled exeption occurs

I forked the library repo and prepared a fix to infer the unit from somewhere else
https://github.com/andrewleech/pyuhoo/pull/1
am preparing also the bump in the homeassistant component itself:
https://github.com/andrewleech/uhoo-homeassistant/pull/6

**Comment by rbhun** [comment]
WowIt works Thank you! Sent from my iPhoneOn 23 Sep 2024, at 01:07, Simone Rescio ***@***.***> wrote:﻿
hi folks
TL;DR

open you uHoo mobile app
tap hamburgher menu
Appearance
Temperature
Change it to whatever else you currently have and save
Change it back to you previous setting

Issue is in the pyuhoo library trying to access the temperature unit selection from somewhere that is not anymore guaranteed to be present, reselecting the unit makes the API return again said field, without which the unhandled exeption occurs
I forked the library repo and prepared a fix to infer the unit from somewhere else
andrewleech/pyuhoo#1
am preparing also the bump in the homeassistant component itself:
#6

**Comment by srescio** [comment]
Fyi the issue i addressed is related specifically to the error reported in https://github.com/andrewleech/uhoo-homeassistant/issues/5
I got confused and referenced this issue instead and later corrected the link

Altough you may try the temp unit reselection regardless to try if it fixes the other problem as well

**Comment by rbhun** [comment]
Well it seems to have immediately fix this issue too, so the answer is still valid. I guess the same issue breaks the first run and reports an error

**Comment by srescio** [comment]
this can be closed
